### ISSUE TITLE
Getting templates from database

### ISSUE THREAD

**Issue by Luctia** [vintasoftware/django-templated-email#128]
So I want to be able to use templating for sending emails, but in my system some users should be able to create templates themselves. Saving these directly in some directory and redeploying every time is a bit of a hassle, so I would like to save these templates in my database and get them when necessary. Is that possible with this package? I can't really find anything on it.

**Comment by fjsj** [comment]
Not possible out of the box right now, but it's possible to implement.
1. You need to inherit from `TemplateBackend` class at https://github.com/vintasoftware/django-templated-email/blob/develop/templated_email/backends/vanilla_django.py
1. Customize the logic for getting the template with `template_name`. The difficult part seems to be the `render_block_to_string` call, as it uses the library [django-render-block](https://github.com/clokep/django-render-block) which uses [Django get_template logic](https://docs.djangoproject.com/en/3.2/topics/templates/#django.template.loader.get_template) to get the template by name.
1. For getting templates by name from the DB perhaps a project [like this one](https://github.com/jazzband/django-dbtemplates) can help.
1. Finally, use your new class as your `TEMPLATED_EMAIL_BACKEND` on settings

Let me know if you see any issues. Closing this issue for now, as I think this is more related to the template engine logic than this package.
