### ISSUE TITLE
Love your package! Do you need help setting up GitHub Actions?

### ISSUE THREAD

**Issue by mpasternak** [vintasoftware/django-templated-email#137]
Hi, 

I love your package, and having written something similar in the past, I just can't get over how cool you did all the stuff. 

Do you need help with setting up the GitHub Actions? Sadly, TravisCI has been non-functional for some time now. 

Regards, 
m

**Comment by fjsj** [comment]
Yes, please feel free to open a PR! Thanks!

**Comment by mpasternak** [comment]
Done! https://github.com/vintasoftware/django-templated-email/pull/140
