### ISSUE TITLE
New PyPI release, maybe?

### ISSUE THREAD

**Issue by mpasternak** [vintasoftware/django-templated-email#138]
Hi, 

I've just hit the bug with the newlines in the subject. 

Looks like it has been already patched: 
https://github.com/vintasoftware/django-templated-email/blob/a5fd5b88ffc63c6cce74516456a29f5f3b465d7c/templated_email/backends/vanilla_django.py#L161

Sadly, it is not on PyPI. Would you like to create a new release anytime soon? Thanks!

**Comment by chocoelho** [comment]
Hey there @mpasternak, a new release is available through Pypi.
