### ISSUE TITLE
Test django-render-block 0.10b1 before release

### ISSUE THREAD

**Issue by clokep** [vintasoftware/django-templated-email#144]
Hey all, I just released a rather large release of django-render-block which rewrites a significant amount of code. I do not want to break django-templated-email and would love if the test suite could be run against version 0.10b1 which should be on pypi now. Thanks so much!

This fixes a couple long-standing bugs in django-render-block and tests against newer Python/Django: https://github.com/clokep/django-render-block/blob/main/CHANGELOG.rst#010b1-july-1-2024

**Comment by fjsj** [comment]
Thank you for the heads up! I will test

**Comment by clokep** [comment]
I briefly tried to do this locally, but unfortunately was unable to get tests running (even without the newer django-render-block).

**Comment by fjsj** [comment]
@clokep I just ran the tests locally and on CI, all good! Thanks for the heads up. https://github.com/vintasoftware/django-templated-email/pull/146
