### ISSUE TITLE
Support {{STATIC_URL}} and {{MEDIA_URL}}

### ISSUE THREAD

**Issue by sunshineo** [vintasoftware/django-templated-email#32]
I hope this is possible. After all, this project is called "django-templated-email"

Thanks

--Gordon

**Comment by sunshineo** [comment]
Wow, people looked at this after 3 years.

**Comment by aericson** [comment]
yea, we are trying to get this back on track. Feel free to reopen if you think it's still makes sense.

**Comment by sunshineo** [comment]
Good luck with that. I have moved on to the node world.
