### ISSUE TITLE
Bump version number on PyPi with new Django 1.8 fix

### ISSUE THREAD

**Issue by bradbeattie** [vintasoftware/django-templated-email#43]
Currently doing a "pip install django-templated-email" will break a Django 1.8 instance as the latest compatibility code hasn't been put into pypi.

**Comment by outime** [comment]
+1

**Comment by aamirtharaj-rpx** [comment]
:+1:

**Comment by flxfxp** [comment]
+1

**Comment by flxfxp** [comment]
Any news on this? It's kinda annoying relying on checking out git instead of a pypi package.

**Comment by palm86** [comment]
Would be much appreciated

**Comment by kennydude** [comment]
At [pebble](https://github.com/mypebble/django-templated-email) we've forked this and pushed it to pypi with django 1.8 support under `django-templated-email-pebble`

**Comment by awbacker** [comment]
@kennydude Thanks.  I guess we should consider django-templated-email as unsupported now.

**Comment by nikulin** [comment]
@kennydude Me too. I suppose this appears when 'extends' tag used in template.

**Comment by BradWhittington** [comment]
I'll gladly give access to someone who is keen to pick up the project and merge PRs etc.

**Comment by chris-erickson** [comment]
Is @aericson the maintainer now whom could perhaps address this?

**Comment by aericson** [comment]
@chris-erickson Hey, will do. Will try to get python3 and django 1.9 (#53 and #54) before this.

**Comment by tysonclugg** [comment]
Please @chris-erickson make a release with this _before_ adding more features.

[Perfect is the enemy of good](https://www.psychologytoday.com/blog/happiness-in-world/201106/why-perfect-is-the-enemy-good).  We'll be waiting for Python 3 and Django 1.9 support regardless, so why not give us the incremental improvement of Django 1.8 support in the interim?

**Comment by chris-erickson** [comment]
@tysonclugg thanks for the development tips, but I think you meant it for @aericson

**Comment by aericson** [comment]
Hey, this has been ready for release for a while. I have been waiting for the original maintainer/author @BradWhittington to give me access to PyPi but until he does I can't do much about it. Haven't gotten an answer from him in ages.

**Comment by aericson** [comment]
Release version 0.5
