### ISSUE TITLE
Using extends kills the subject

### ISSUE THREAD

**Issue by oliwarner** [vintasoftware/django-templated-email#57]
`base.email`

    {% block html %}
        my html
        {% block body %}{% endblock %}
        more html
    {% endblock %}

`myemail.email`

    {% extends 'emails/base.email' %}
    {% block subject %} banana {% endblock %}
    {% block body %}my body{% endblock %}

I run DTE against `myemail`. The body/HTML side of things is working great, but the subject is completely ignored. If I add a subject tag to the `base.email` it will use that, but won't let me override it from `myemail.email`.

Am I structuring this incorrectly?

**Comment by clokep** [comment]
My guess is that you want to include the `subject` block in the base template too, just leave it empty if you don't have content for it there.
