### ISSUE TITLE
Templated email example with generic CRUD

### ISSUE THREAD

**Issue by sunjoomoon** [vintasoftware/django-templated-email#59]
Following https://docs.djangoproject.com/en/1.8/topics/class-based-views/generic-editing/ 

#  views.py
```
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from myapp.models import Author

class AuthorCreate(CreateView):
    model = Author
    fields = ['name','email']

class AuthorUpdate(UpdateView):
    model = Author
    fields = ['name','email']

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('author-list')
```

I am trying to figure out how django-templated-email  can be used to send email  to the  user's 'email' field and to 'settings.MANAGERS' upon Author creation and Update. Any example or hint will be cool.  The hardest part is how all fit together, piece by piece makes sense though.

**Comment by aericson** [comment]
Hey, sorry we never got to answer this, the project was dead back then. I'm closing this but we created a Gitter channel for people to get faster feedback with this kind of things now. There is a badge on the README with a link to it.

If you still need help drop by there.
https://gitter.im/vintasoftware/django-templated-email
