### ISSUE TITLE
Move project to Jazzband

### ISSUE THREAD

**Issue by tysonclugg** [vintasoftware/django-templated-email#61]
[Jazzband](https://jazzband.co/) is a project to share responsibility for administration of open source projects. django-templated-email is a good candidate because:

* The project is mature and [widely used](http://pypi-ranking.info/module/django-templated-email).
* By moving to jazzband, its easier for contributors to merge changes and make official releases. In the best case, this will spark some additional contribution to fix long broken features. In the worst case, the people that really need support for the latest Django will be able to publish a compatible version.

To move to jazzband, follow the [guidelines](https://jazzband.co/about/guidelines).

**Comment by aericson** [comment]
Thanks for the hint. We might consider it in the future but we are focusing efforts on the project at the moment.
