### ISSUE TITLE
Email inliner support

### ISSUE THREAD

**Issue by macmichael01** [vintasoftware/django-templated-email#62]
There is a tool called django-inliner which works well. Maybe there is a way to integrate into this project somehow.

**Comment by aericson** [comment]
Can you provide a link to the lib? Haven't found it and didn't really understand the problem.

**Comment by macmichael01** [comment]
https://github.com/roverdotcom/django-inlinecss.

**Comment by aericson** [comment]
This works effortlessly out of the box. Just follow their README. Just use their template tags in the template file.

**Comment by macmichael01** [comment]
I thought that there could be a more integrated approach as well as a possible MJML integration. Obviously both of these types of support could be added within the template. I don't know what the rendering times are for doing such things but calling the inliner within the django templated email would seem like extra overhead. Perhaps a more integrated support of this would help. If a project does not have some sort of task queue setup the user will have to wait until this is rendered and sent out. Maybe I don't know what I am talking about :p but I just though it would be nice to have a single django app plugin that provides all of these nice email templating tools for you.

**Comment by aericson** [comment]
I think this is out of the scope of the project for now. About rendering times I don't think they are the bottleneck here. The actual sending of the email takes considerably more time than the rendering.
