### ISSUE TITLE
Migrating the project

### ISSUE THREAD

**Issue by aericson** [vintasoftware/django-templated-email#64]
Even though I have permission to commit in this repository I don't have permission to publish it in pypi. We lost touch with the old developer @BradWhittington .

I will leave this issue open for a few days and if there is no objection we will create a new Pypi package and migrate the project there, that's the only way to go forward with the project.

**Comment by zoidbergwill** [comment]
@aericson I work with @BradWhittington and can get in contact with him. It'd be easier for users if we get you access to PyPI for the package, and potentially migrate the project to your GitHub repo.

**Comment by aericson** [comment]
@zoidbergwill That would be ideal if you can get him to do these two things. Let me know if you need anything from me.

**Comment by BradWhittington** [comment]
I've given @aericson permission on pypi, assuming that's your username there...

**Comment by aericson** [comment]
Thanks!
